openapi: 3.0.0
info:
  title: 'MarsDex'
  description: 'MarsDex is a resource indexing tool that you can use to know where you nee dto go to find the things you need.'
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: 'Local development implementation'
  - url: https://project-ii.ti.howest.be/mars-23
    description: 'Public web api'
paths:
  /api/message:
    get:
      description: Get a nice message
      operationId: getMessage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /api/company/{id}/resource:
    get:
      summary: Return resources of a given company
      description: Return resources of a company based on it's id.
      parameters:
        - name: id
          in: path
          required: true
          description: Id that identifies a company.
          schema:
            type: string
      responses:
        '200':
          description: Returns all company's resources in a JSON Array
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    resources:
                      type: object
                      properties:
                        weight:
                          type: integer
                        added:
                          type: string
                          format: date
                        rarity:
                          type: integer


        '404':
          description: The requested company couldn't be found
        '500':
          description: Something has gone wrong on our side