openapi: 3.0.0
info:
  title: 'Mars Concept Title'
  description: 'Please complete this spec as seen in the module Information Module'
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: 'Local development implementation'
  - url: https://project-ii.ti.howest.be/mars-23
    description: 'Public web api'
paths:
  /api/message:
    get:
      description: Get a nice message
      operationId: getMessage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /api/company/{id}:
    get:
      description: get information about the company with given ID
      operationId: GetCompanyByID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: all information about company Id =id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    colony:
                      type: string
                    name:
                      type: string
                    Email:
                      type: string
                    PhoneNumber:
                      type: number
        '404':
            description: Id not found
        '500':
            description: Server side Issue thats our fault